
all: 
	-pdflatex 2013-diversity.tex 
	-bibtex 2013-diversity 
	-pdflatex 2013-diversity.tex 
	-pdflatex 2013-diversity.tex 


clean:
	-rm -r 2013-diversity.pdf *.bbl *.blg *.aux *.log *.lot *.lof *.toc 
