curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS014124.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS014271.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS015038.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS015057.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS015537.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS015893.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS016037.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS016501.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS016740.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS019327.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS020856.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS022621.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS022719.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS023617.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS024375.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS024441.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS042131.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS042910.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS049389.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS050244.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS053603.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS054687.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS057205.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS063932.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS078182.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/vaginal_introitus/SRS062752.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/buccal_mucosa/SRS065431.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/buccal_mucosa/SRS075406.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/buccal_mucosa/SRS077738.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/palatine_tonsils/SRS019126.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/posterior_fornix/SRS011584.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/posterior_fornix/SRS012294.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/posterior_fornix/SRS017520.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/posterior_fornix/SRS017700.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/posterior_fornix/SRS020349.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/posterior_fornix/SRS024068.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/posterior_fornix/SRS024428.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/posterior_fornix/SRS048536.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/posterior_fornix/SRS050184.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/posterior_fornix/SRS065347.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/posterior_fornix/SRS075419.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/posterior_fornix/SRS078197.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/right_retroauricular_crease/SRS024598.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/right_retroauricular_crease/SRS045606.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/right_retroauricular_crease/SRS052988.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/saliva/SRS014692.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS011084.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS011134.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS011452.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS013951.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS014613.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS014979.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/anterior_nares/SRS012663.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/anterior_nares/SRS014682.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/anterior_nares/SRS015793.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/anterior_nares/SRS015937.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/anterior_nares/SRS016581.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/anterior_nares/SRS019019.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/anterior_nares/SRS019039.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/anterior_nares/SRS019215.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/anterior_nares/SRS019597.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/anterior_nares/SRS022129.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/anterior_nares/SRS023847.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/anterior_nares/SRS024424.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/anterior_nares/SRS062713.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/anterior_nares/SRS063035.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/anterior_nares/SRS063178.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/attached_keratinized_gingiva/SRS013946.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/buccal_mucosa/SRS011247.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/buccal_mucosa/SRS011310.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/buccal_mucosa/SRS013239.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/buccal_mucosa/SRS013506.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/buccal_mucosa/SRS014686.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/buccal_mucosa/SRS015059.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/buccal_mucosa/SRS015540.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/buccal_mucosa/SRS015646.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/buccal_mucosa/SRS016039.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS054956.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS057717.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS058723.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS064557.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS064645.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS065504.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/subgingival_plaque/SRS015064.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/supragingival_plaque/SRS013252.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/supragingival_plaque/SRS015158.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/supragingival_plaque/SRS015755.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/supragingival_plaque/SRS015947.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/supragingival_plaque/SRS016043.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/supragingival_plaque/SRS016200.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/supragingival_plaque/SRS017139.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/supragingival_plaque/SRS019028.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/supragingival_plaque/SRS047113.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/supragingival_plaque/SRS049268.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/supragingival_plaque/SRS052876.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/buccal_mucosa/SRS016600.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/buccal_mucosa/SRS017127.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/buccal_mucosa/SRS017537.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/buccal_mucosa/SRS017687.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/buccal_mucosa/SRS017810.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/buccal_mucosa/SRS019124.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/buccal_mucosa/SRS020222.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/buccal_mucosa/SRS020858.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/buccal_mucosa/SRS024347.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/buccal_mucosa/SRS024557.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/buccal_mucosa/SRS045262.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/buccal_mucosa/SRS048719.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/buccal_mucosa/SRS050628.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS015264.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS015782.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS015960.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS016495.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS016517.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS017103.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS018313.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS018575.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS019267.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS019787.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS019910.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS020869.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS021484.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS023176.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS023526.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS023971.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS024331.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS024435.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS048870.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS049900.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS049959.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS049995.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS050299.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS050752.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS052027.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS011115.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS011306.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS013234.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS013502.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS013705.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS014573.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS014888.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS015174.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS015644.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS015762.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS015941.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS016002.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS016342.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS018300.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS018739.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS018791.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS018969.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS019045.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS019071.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS019122.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS019219.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS019389.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS020334.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS022143.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS022530.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS044486.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS045715.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS048411.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS049147.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS050669.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS055495.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS056323.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS057791.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS062761.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS063193.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS064423.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS075404.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/vaginal_introitus/SRS015071.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/buccal_mucosa/SRS065133.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/hard_palate/SRS062878.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/left_retroauricular_crease/SRS017849.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/left_retroauricular_crease/SRS019015.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/left_retroauricular_crease/SRS019063.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/left_retroauricular_crease/SRS020261.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/left_retroauricular_crease/SRS024596.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/mid_vagina/SRS014466.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/palatine_tonsils/SRS013947.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/palatine_tonsils/SRS014474.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/palatine_tonsils/SRS063351.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/posterior_fornix/SRS011355.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/posterior_fornix/SRS014629.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS012273.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS013158.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS014313.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS015133.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/anterior_nares/SRS011105.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/anterior_nares/SRS012291.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/anterior_nares/SRS013637.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/anterior_nares/SRS014901.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/anterior_nares/SRS015269.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/anterior_nares/SRS015450.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/anterior_nares/SRS015752.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/anterior_nares/SRS016292.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/anterior_nares/SRS016434.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/anterior_nares/SRS016513.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/anterior_nares/SRS017044.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/anterior_nares/SRS017156.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/anterior_nares/SRS017820.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/anterior_nares/SRS018671.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/anterior_nares/SRS018981.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/anterior_nares/SRS019067.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/anterior_nares/SRS019986.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/anterior_nares/SRS020868.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/anterior_nares/SRS022645.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/anterior_nares/SRS047225.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/anterior_nares/SRS047254.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/anterior_nares/SRS047708.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/anterior_nares/SRS047844.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/anterior_nares/SRS053437.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/anterior_nares/SRS056906.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/attached_keratinized_gingiva/SRS014473.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/attached_keratinized_gingiva/SRS014687.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/attached_keratinized_gingiva/SRS015060.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/buccal_mucosa/SRS012281.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/buccal_mucosa/SRS014126.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/buccal_mucosa/SRS014472.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/buccal_mucosa/SRS015040.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/buccal_mucosa/SRS015436.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/buccal_mucosa/SRS015799.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/buccal_mucosa/SRS016088.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/buccal_mucosa/SRS016196.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS053335.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS054590.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS063040.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS077730.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS078176.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/subgingival_plaque/SRS019029.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/supragingival_plaque/SRS013170.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/supragingival_plaque/SRS013533.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/supragingival_plaque/SRS013836.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/supragingival_plaque/SRS014578.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/supragingival_plaque/SRS015063.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/supragingival_plaque/SRS015650.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/supragingival_plaque/SRS015899.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/supragingival_plaque/SRS015989.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/supragingival_plaque/SRS016092.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/supragingival_plaque/SRS016360.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/supragingival_plaque/SRS016541.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/supragingival_plaque/SRS016746.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/supragingival_plaque/SRS017088.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/supragingival_plaque/SRS017304.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/supragingival_plaque/SRS017445.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/supragingival_plaque/SRS017691.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/supragingival_plaque/SRS017814.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/supragingival_plaque/SRS018157.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/supragingival_plaque/SRS024144.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/supragingival_plaque/SRS024649.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/supragingival_plaque/SRS047634.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/supragingival_plaque/SRS053630.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/supragingival_plaque/SRS053917.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/buccal_mucosa/SRS016533.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/buccal_mucosa/SRS017013.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/buccal_mucosa/SRS018661.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/buccal_mucosa/SRS019587.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/buccal_mucosa/SRS019976.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/buccal_mucosa/SRS022079.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/buccal_mucosa/SRS023534.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/buccal_mucosa/SRS023987.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/buccal_mucosa/SRS024140.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/buccal_mucosa/SRS043676.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/buccal_mucosa/SRS045254.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/buccal_mucosa/SRS046686.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS015369.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS015890.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS016018.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS016095.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS016753.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS016954.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS017521.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS057478.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS064276.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS075398.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/subgingival_plaque/SRS014107.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/subgingival_plaque/SRS014691.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/supragingival_plaque/SRS011126.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/supragingival_plaque/SRS011255.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/supragingival_plaque/SRS012285.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/supragingival_plaque/SRS013949.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/supragingival_plaque/SRS014476.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/supragingival_plaque/SRS015278.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/supragingival_plaque/SRS016331.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/supragingival_plaque/SRS017025.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/supragingival_plaque/SRS018337.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/supragingival_plaque/SRS018573.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/supragingival_plaque/SRS018665.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/supragingival_plaque/SRS019225.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/supragingival_plaque/SRS019387.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/supragingival_plaque/SRS019980.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/supragingival_plaque/SRS020340.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/supragingival_plaque/SRS022536.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/supragingival_plaque/SRS023538.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/supragingival_plaque/SRS023938.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/supragingival_plaque/SRS023964.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/supragingival_plaque/SRS024381.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/supragingival_plaque/SRS024561.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/supragingival_plaque/SRS044366.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/supragingival_plaque/SRS047265.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/supragingival_plaque/SRS051930.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/supragingival_plaque/SRS051941.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/supragingival_plaque/SRS053584.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/supragingival_plaque/SRS058053.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/buccal_mucosa/SRS018149.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/buccal_mucosa/SRS018443.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/buccal_mucosa/SRS018971.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/buccal_mucosa/SRS019073.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/buccal_mucosa/SRS019221.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/buccal_mucosa/SRS022145.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/buccal_mucosa/SRS022625.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/buccal_mucosa/SRS024377.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/buccal_mucosa/SRS024470.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/buccal_mucosa/SRS042457.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/buccal_mucosa/SRS043646.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/buccal_mucosa/SRS049283.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/buccal_mucosa/SRS050029.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/buccal_mucosa/SRS054776.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/buccal_mucosa/SRS056157.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS015431.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS015794.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS016267.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS016585.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS017247.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS018817.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS019068.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS019381.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS019397.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS021948.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS022524.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS023346.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS023914.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS024075.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS042284.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS043411.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS043701.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS045645.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS049164.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/supragingival_plaque/SRS064219.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/supragingival_plaque/SRS064329.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/supragingival_plaque/SRS064449.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/supragingival_plaque/SRS064493.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS013164.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS015209.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS015434.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS016319.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS016569.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS017007.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS017439.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS017533.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS017808.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS018145.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS018357.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS018591.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS019974.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS021496.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS021954.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS023958.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS024637.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS042643.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS043663.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS055426.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS056622.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS057355.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS057692.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS058336.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS062544.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS064774.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/vaginal_introitus/SRS014465.tar.bz2


