curl -O http://downloads.hmpdacc.org/data/Illumina/attached_keratinized_gingiva/SRS019025.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/buccal_mucosa/SRS011090.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/buccal_mucosa/SRS011144.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/buccal_mucosa/SRS013825.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/buccal_mucosa/SRS013881.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/buccal_mucosa/SRS013945.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/buccal_mucosa/SRS015374.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS053398.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS056519.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS057478.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS064276.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS075398.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/subgingival_plaque/SRS014107.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/subgingival_plaque/SRS014691.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/supragingival_plaque/SRS011126.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/supragingival_plaque/SRS011255.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/supragingival_plaque/SRS012285.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/supragingival_plaque/SRS013949.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/supragingival_plaque/SRS014476.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/supragingival_plaque/SRS015278.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/supragingival_plaque/SRS016331.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/supragingival_plaque/SRS017025.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/supragingival_plaque/SRS018337.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/supragingival_plaque/SRS018573.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/supragingival_plaque/SRS018665.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/supragingival_plaque/SRS019225.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/supragingival_plaque/SRS019387.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/supragingival_plaque/SRS019980.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/supragingival_plaque/SRS020340.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/supragingival_plaque/SRS022536.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/supragingival_plaque/SRS023538.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/supragingival_plaque/SRS023938.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/supragingival_plaque/SRS023964.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/supragingival_plaque/SRS024381.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/supragingival_plaque/SRS024561.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/supragingival_plaque/SRS044366.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/supragingival_plaque/SRS047265.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/supragingival_plaque/SRS051930.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/supragingival_plaque/SRS051941.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/supragingival_plaque/SRS053584.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/supragingival_plaque/SRS058053.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/buccal_mucosa/SRS018149.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/buccal_mucosa/SRS018443.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/buccal_mucosa/SRS018971.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/buccal_mucosa/SRS019073.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/buccal_mucosa/SRS019221.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/buccal_mucosa/SRS022145.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/buccal_mucosa/SRS022625.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/buccal_mucosa/SRS024377.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/buccal_mucosa/SRS024470.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/buccal_mucosa/SRS042457.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/buccal_mucosa/SRS043646.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/buccal_mucosa/SRS049283.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/buccal_mucosa/SRS050029.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/buccal_mucosa/SRS054776.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/buccal_mucosa/SRS056157.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS015431.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS015794.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS016267.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS016585.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS017247.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS018817.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS019068.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS019381.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS019397.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS021948.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS022524.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS023346.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS023914.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS024075.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS042284.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS043411.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS043701.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS045645.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS049164.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/supragingival_plaque/SRS064219.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/supragingival_plaque/SRS064329.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/supragingival_plaque/SRS064449.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/supragingival_plaque/SRS064493.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS013164.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS015209.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS015434.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS016319.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS016569.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS017007.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS017439.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS017533.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS017808.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS018145.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS018357.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS018591.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS019974.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS021496.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS021954.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS023958.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS024637.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS042643.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS043663.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS055426.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS056622.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS057355.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS057692.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS058336.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS062544.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS064774.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/vaginal_introitus/SRS014465.tar.bz2
