
curl -O http://downloads.hmpdacc.org/data/Illumina/supragingival_plaque/SRS021477.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/supragingival_plaque/SRS023595.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/supragingival_plaque/SRS023841.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/supragingival_plaque/SRS024021.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/supragingival_plaque/SRS024447.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/supragingival_plaque/SRS043018.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/supragingival_plaque/SRS047100.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/supragingival_plaque/SRS047113.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/supragingival_plaque/SRS049268.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/supragingival_plaque/SRS052876.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/buccal_mucosa/SRS016600.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/buccal_mucosa/SRS017127.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/buccal_mucosa/SRS017537.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/buccal_mucosa/SRS017687.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/buccal_mucosa/SRS017810.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/buccal_mucosa/SRS019124.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/buccal_mucosa/SRS020222.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/buccal_mucosa/SRS020858.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/buccal_mucosa/SRS024347.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/buccal_mucosa/SRS024557.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/buccal_mucosa/SRS045262.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/buccal_mucosa/SRS048719.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/buccal_mucosa/SRS050628.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS015264.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS015782.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS015960.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS016495.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS016517.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS017103.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS018313.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS018575.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS019267.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS019787.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS019910.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS020869.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS021484.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS023176.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS023526.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS023971.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS024331.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS024435.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS048870.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS049900.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS049959.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS049995.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS050299.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS050752.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS052027.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS011115.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS011306.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS013234.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS013502.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS013705.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS014573.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS014888.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS015174.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS015644.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS015762.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS015941.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS016002.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS016342.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS018300.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS018739.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS018791.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS018969.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS019045.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS019071.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS019122.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS019219.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS019389.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS020334.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS022143.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS022530.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS044486.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS045715.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS048411.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS049147.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS050669.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS055495.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS056323.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS057791.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS062761.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS063193.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS064423.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS075404.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/vaginal_introitus/SRS015071.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/buccal_mucosa/SRS065133.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/hard_palate/SRS062878.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/left_retroauricular_crease/SRS017849.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/left_retroauricular_crease/SRS019015.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/left_retroauricular_crease/SRS019063.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/left_retroauricular_crease/SRS020261.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/left_retroauricular_crease/SRS024596.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/mid_vagina/SRS014466.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/palatine_tonsils/SRS013947.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/palatine_tonsils/SRS014474.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/palatine_tonsils/SRS063351.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/posterior_fornix/SRS011355.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/posterior_fornix/SRS014629.tar.bz2