
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS017821.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS018133.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS019030.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS019685.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS022713.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS023829.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS024388.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS042628.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS047014.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS048164.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS049712.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS051882.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/supragingival_plaque/SRS065099.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/supragingival_plaque/SRS075410.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/throat/SRS013948.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/throat/SRS015062.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/throat/SRS019027.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/throat/SRS019127.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/throat/SRS065335.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS014470.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS014684.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS015272.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS015395.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS016225.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS016529.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS017076.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS017120.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS017713.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS018439.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS019022.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS019607.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS020220.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS023557.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS023926.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS024015.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS024138.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS024277.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS024318.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS024580.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS044373.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS047219.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS051791.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS053854.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS063288.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS077736.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/buccal_mucosa/SRS056892.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/buccal_mucosa/SRS058105.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/buccal_mucosa/SRS063287.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/buccal_mucosa/SRS063478.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/buccal_mucosa/SRS064809.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/left_retroauricular_crease/SRS024482.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/left_retroauricular_crease/SRS024620.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/posterior_fornix/SRS011111.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/posterior_fornix/SRS015054.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/posterior_fornix/SRS015168.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/posterior_fornix/SRS015425.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/posterior_fornix/SRS016191.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/posterior_fornix/SRS018769.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/posterior_fornix/SRS019989.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/posterior_fornix/SRS021969.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/posterior_fornix/SRS022545.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/posterior_fornix/SRS022734.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/posterior_fornix/SRS042428.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/posterior_fornix/SRS047335.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/posterior_fornix/SRS051505.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/posterior_fornix/SRS055298.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/posterior_fornix/SRS056695.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/posterior_fornix/SRS077751.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/right_retroauricular_crease/SRS013261.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/right_retroauricular_crease/SRS017851.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/right_retroauricular_crease/SRS019081.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/right_retroauricular_crease/SRS058221.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/saliva/SRS013942.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS011061.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS011271.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS013521.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS013687.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS013800.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS014235.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS014287.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS014683.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/anterior_nares/SRS011397.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/anterior_nares/SRS013155.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/anterior_nares/SRS013269.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/anterior_nares/SRS013956.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/anterior_nares/SRS014464.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/anterior_nares/SRS015051.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/anterior_nares/SRS016553.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/anterior_nares/SRS016752.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/anterior_nares/SRS018312.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/anterior_nares/SRS019339.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/anterior_nares/SRS020232.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/anterior_nares/SRS020386.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/anterior_nares/SRS022006.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/anterior_nares/SRS023212.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/anterior_nares/SRS024064.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/anterior_nares/SRS024301.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/anterior_nares/SRS044626.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/anterior_nares/SRS046344.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/anterior_nares/SRS050025.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/anterior_nares/SRS051600.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/anterior_nares/SRS056210.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/anterior_nares/SRS065179.tar.bz2
