curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS052697.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS053214.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/supragingival_plaque/SRS058808.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/supragingival_plaque/SRS063603.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/throat/SRS014475.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/throat/SRS014689.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS011086.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS014124.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS014271.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS015038.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS015057.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS015537.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS015893.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS016037.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS016501.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS016740.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS019327.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS020856.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS022621.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS022719.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS023617.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS024375.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS024441.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS042131.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS042910.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS049389.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS050244.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS053603.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS054687.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS057205.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS063932.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/tongue_dorsum/SRS078182.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/vaginal_introitus/SRS062752.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/buccal_mucosa/SRS065431.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/buccal_mucosa/SRS075406.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/buccal_mucosa/SRS077738.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/palatine_tonsils/SRS019126.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/posterior_fornix/SRS011584.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/posterior_fornix/SRS012294.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/posterior_fornix/SRS017520.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/posterior_fornix/SRS017700.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/posterior_fornix/SRS020349.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/posterior_fornix/SRS024068.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/posterior_fornix/SRS024428.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/posterior_fornix/SRS048536.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/posterior_fornix/SRS050184.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/posterior_fornix/SRS065347.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/posterior_fornix/SRS075419.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/posterior_fornix/SRS078197.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/right_retroauricular_crease/SRS024598.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/right_retroauricular_crease/SRS045606.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/right_retroauricular_crease/SRS052988.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/saliva/SRS014692.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS011084.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS011134.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS011452.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS013951.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS014613.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS014979.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/anterior_nares/SRS012663.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/anterior_nares/SRS014682.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/anterior_nares/SRS015793.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/anterior_nares/SRS015937.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/anterior_nares/SRS016581.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/anterior_nares/SRS019019.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/anterior_nares/SRS019039.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/anterior_nares/SRS019215.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/anterior_nares/SRS019597.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/anterior_nares/SRS022129.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/anterior_nares/SRS023847.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/anterior_nares/SRS024424.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/anterior_nares/SRS062713.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/anterior_nares/SRS063035.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/anterior_nares/SRS063178.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/attached_keratinized_gingiva/SRS013946.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/buccal_mucosa/SRS011247.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/buccal_mucosa/SRS011310.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/buccal_mucosa/SRS013239.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/buccal_mucosa/SRS013506.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/buccal_mucosa/SRS014686.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/buccal_mucosa/SRS015059.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/buccal_mucosa/SRS015540.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/buccal_mucosa/SRS015646.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/buccal_mucosa/SRS016039.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS054956.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS057717.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS058723.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS064557.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS064645.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/stool/SRS065504.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/subgingival_plaque/SRS015064.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/supragingival_plaque/SRS013252.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/supragingival_plaque/SRS015158.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/supragingival_plaque/SRS015755.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/supragingival_plaque/SRS015947.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/supragingival_plaque/SRS016043.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/supragingival_plaque/SRS016200.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/supragingival_plaque/SRS017139.tar.bz2
curl -O http://downloads.hmpdacc.org/data/Illumina/supragingival_plaque/SRS019028.tar.bz2